snd-soc-s3c2440-myjz2440-dma-objs := myjz2440-dma.o
snd-soc-s3c2440-myjz2440-iis-objs := myjz2440-iis.o

obj-$(CONFIG_SND_SOC_SAMSUNG_MYALSA_S3C2440_I2S) += snd-soc-s3c2440-myjz2440-dma.o
obj-$(CONFIG_SND_SOC_SAMSUNG_MYALSA_S3C2440_DMA) += snd-soc-s3c2440-myjz2440-iis.o
