#KERN_DIR = /home/xiao/Documents/work1/linux-3.4.2

#all:
#	make -C $(KERN_DIR) M=`pwd` modules 

#clean:
#	make -C $(KERN_DIR) M=`pwd` modules clean
#	rm -rf modules.order


obj-$(CONFIG_SND_SOC_SAMSUNG_MYALSA_S3C2440)   += machine/ platform/

